# Numpy

Numpy是Python做数据分析所必须要掌握的基础库之一。
整理自[Github开源项目](https://github.com/rougier/numpy-100)(部分题目保留了原文作参考)

#### 1. 导入```numpy```库并简写为 `np` (★☆☆) 
(**提示**: ```import … as …```)

In [1]:
import numpy as np

#### 2. 打印```numpy```的版本和配置说明 (★☆☆) 
(**提示**: ```np.__version__, np.show_config```)

#### 4.  如何找到任何一个数组的内存大小？ (★☆☆)
(**提示**: ```size, itemsize```)

In [20]:
Z = np.zeros((10,10),dtype=np.float64)
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 9.  创建一个 ```3x3``` 并且值从0到8的矩阵(★☆☆) 
(**提示**: ```reshape```)

In [ ]:
# Z = np.arange(9).reshape(3,3)
# print(Z)

#### 10. 找到数组```[1,2,0,0,4,0]```中非0元素的位置索引 (★☆☆) 
(**提示**: ```np.nonzero```)

In [7]:
nz = np.nonzero([1,2,0,0,4,0])
nz
# help(np.nonzero)

(array([0, 1, 4]),)

#### 11. 创建一个 ```3x3``` 的单位矩阵 (★☆☆) 
(**提示**: ```np.eye```)

In [32]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. 创建一个 ```3x3x3```的随机数组 (★☆☆) 
(**提示**: ```np.random.random```)

In [33]:
# Z = np.random.random((3,3,3))
help(np.random.random)


Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



#### 13. 创建一个 ```10x10``` 的随机数组并找到它的最大值和最小值 (★☆☆) 
(**提示**: ```min, max```)

In [34]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.009689174232655584 0.9610600777455623


#### 14. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆) 
(**提示**: ```mean```)

In [36]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.40648201025705116


#### 16. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆) 
(**提示**: ```np.pad```)

In [8]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. 以下表达式运行的结果分别是什么? (★☆☆) 
(**提示**: ```NaN = not a number, inf = infinity```)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

#### 18. 创建一个 ```5x5```的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆) 
(**提示**: ```np.diag```)

In [13]:
Z = np.diag(np.arange(1,5),k=-1)
print(Z)



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. 创建一个``` 8x8``` 的矩阵，并且设置成棋盘样式 (★☆☆) 
(**提示**: ```array[::2]```)

In [45]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 21. 用```tile```函数去创建一个 ```8x8```的棋盘样式矩阵(★☆☆) 
(**提示**: ```np.tile```)

In [47]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么? 
(**提示**: ```np.unravel_index```)

In [46]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 22. 对一个```5x5```的随机矩阵做归一化(★☆☆) 
(**提示**: ```(x - min) / (max - min)```)

In [48]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.36466591 0.0279413  0.35636311 0.89459109 0.16215102]
 [0.292444   0.93150949 0.82267054 0.82681618 0.89341253]
 [0.10774386 0.33972593 0.25920418 0.68453304 1.        ]
 [0.75649952 0.00291049 0.25870875 0.68347215 0.45449789]
 [0.69835411 0.92451752 0.32423659 0.96609378 0.        ]]


#### 24. 一个```5x3```的矩阵与一个```3x2```的矩阵相乘，实矩阵乘积是什么？ (★☆☆) 
(**提示**: ```np.dot | @```)

In [52]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆) 
(**提示**: ```>, <=```)

In [62]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. 下面脚本运行后的结果是什么? (★☆☆) 
(**提示**: np.sum)
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:
print(sum(range(5),-1))

9


In [61]:
from numpy import *
print(np.sum(range(5),-1))


10


#### 28. 下列表达式的结果分别是什么?(★☆☆) 
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [65]:
print(np.array(0) / np.array(0))

nan


<ipython-input-65-a69a51a14444>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


In [66]:
print(np.array(0) // np.array(0))

0


<ipython-input-66-e29d1dbbd607>:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [67]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


#### 29. 如何从零位对浮点数组做舍入 ? (★☆☆) 
(**提示**: ```np.uniform, np.copysign, np.ceil, np.abs```)

In [ ]:
# Z = np.random.uniform(-10,+10,10)
# print (np.copysign(np.ceil(np.abs(Z)), Z))

#### 30. 如何找到两个数组中的共同元素? (★☆☆) 
(**提示**: ```np.intersect1d```)

In [68]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 7 8 9]


#### 33. 如何得到昨天，今天，明天的日期? (★☆☆) 
(**提示**: ```np.datetime64, np.timedelta64```)

In [ ]:
# yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
# today     = np.datetime64('today', 'D')
# tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
# print ("Yesterday is " + str(yesterday))
# print ("Today is " + str(today))
# print ("Tomorrow is "+ str(tomorrow))

#### 34. 如何得到所有与2016年7月对应的日期？ (★★☆) 
(**提示**: ```np.arange(dtype=datetime64['D'])```)

In [ ]:
# Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
# print(Z)

#### 35. 如何直接在位计算```(A+B)\*(-A/2)```(不建立副本)? (★★☆) 
(**提示**: ```np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)```)

In [ ]:
# A = np.ones(3)*1
# B = np.ones(3)*2
# C = np.ones(3)*3
# np.add(A,B,out=B)

In [ ]:
# np.divide(A,2,out=A)

In [ ]:
# np.negative(A,out=A)

In [ ]:
# np.multiply(A,B,out=A)

#### 36. 用五种不同的方法去提取一个随机数组的整数部分(★★☆) 
(**提示**: ```%, np.floor, np.ceil, astype, np.trunc```)

In [ ]:
# Z = np.random.uniform(0,10,10)

# print (Z - Z%1)

In [ ]:
# print (np.floor(Z))

In [ ]:
# print (np.ceil(Z)-1)

In [ ]:
# print (Z.astype(int))

In [ ]:
# print (np.trunc(Z))

#### 37. 创建一个```5x5```的矩阵，其中每行的数值范围从0到4 (★★☆) 
(**提示**: ```np.arange```)

In [83]:
%timeit Z= np.zeros((5,5)) + np.arange(5)
z

2.91 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [82]:
# Z = np.zeros((5,5))
# Z += np.arange(5)
# print (Z)
%timeit  z = np.tile(np.arange(5),(4,1))
z

6.24 µs ± 855 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆) 
(**提示**: ```np.fromiter```)

In [84]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆) 
(**提示**: ```np.linspace```)

In [87]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)
# ?np.linspace


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. 创建一个长度为10的随机向量，并将其排序 (★★☆) 
(**提示**: ```sort```)

In [14]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.0508171  0.06315707 0.10991355 0.22900126 0.34470242 0.35406769
 0.62500525 0.73937055 0.84826013 0.9939231 ]


#### 41.对于一个小数组，如何用比 ```np.sum```更快的方式对其求和？(★★☆) 
(**提示**: ```np.add.reduce```)

In [3]:
# Z = np.arange(10)
?np.add.reduce

#### 42. 对于两个随机数组A和B，检查它们是否相等(★★☆) 
(**提示**: ```np.allclose, np.array_equal```)

In [4]:
# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
# # Assuming identical shape of the arrays and a tolerance for the comparison of values
# equal = np.allclose(A,B)
# print(equal)
?np.allclose

In [5]:
# # 方法2
# # Checking both the shape and the element values, no tolerance (values have to be exactly equal)
# equal = np.array_equal(A,B)
# print(equal)
?np.array_equal


#### 43. 创建一个只读数组(read-only) (★★☆) 
(**提示**: ```flags.writeable```)

```python
# 使用如下过程实现
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-6fd4c6570dd1> in <module>()
      1 Z = np.zeros(10)
      2 Z.flags.writeable = False
----> 3 Z[0] = 1

ValueError: assignment destination is read-only
```

#### 44. 将笛卡尔坐标下的一个```10x2```的矩阵转换为极坐标形式(★★☆) 
(**hint**: ```np.sqrt, np.arctan2```)

In [ ]:
# Z = np.random.random((10,2))
# X,Y = Z[:,0], Z[:,1]
# R = np.sqrt(X**2+Y**2)
# T = np.arctan2(Y,X)
# print (R)
# print (T)

#### 45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆) 
(**提示**: ```argmax```)

In [6]:
Z = np.random.random(10)
Z[Z.argmax()] = -1
print (Z)

[ 0.0771782   0.03716868  0.16312682  0.55173538  0.63799936  0.72685552
  0.81938497  0.82673075  0.10089288 -1.        ]


#### 46. 创建一个结构化数组，并实现 `x` 和 `y` 坐标覆盖 ```[0,1]x[0,1]``` 区域 (★★☆) 
(**提示**: ```np.meshgrid```)

In [7]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. 给定两个数组```X```和```Y```，构造Cauchy矩阵C ```(Cij =1/(xi - yj))```
(**提示**: ```np.subtract.outer```)

In [ ]:
# X = np.arange(8)
# Y = X + 0.5
# C = 1.0 / np.subtract.outer(X, Y)
# print(np.linalg.det(C))

#### 48. 打印每个numpy标量类型的最小值和最大值？ (★★☆) 
(**提示**: ```np.iinfo, np.finfo, eps```)

In [ ]:
# for dtype in [np.int8, np.int32, np.int64]:
#     print(np.iinfo(dtype).min)
#     print(np.iinfo(dtype).max)

# for dtype in [np.float32, np.float64]:
#     print(np.finfo(dtype).min)
#     print(np.finfo(dtype).max)
#     print(np.finfo(dtype).eps)

#### 49. 如何打印一个数组中的所有数值? (★★☆) 
(**提示**: ```np.set_printoptions```)

In [16]:
import sys
np.set_printoptions(threshold=np.inf)
Z = np.zeros((20,20))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. 给定标量时，如何找到数组中最接近标量的值？(★★☆) 
(**提示**: ```argmin```)

In [ ]:
# Z = np.arange(100)
# v = np.random.uniform(0,100)
# index = (np.abs(Z-v)).argmin()
# print (Z[index])

#### 51. 创建一个表示位置```(x,y)```和颜色```(r,g,b)```的结构化数组(★★☆) 
(**提示**: ```dtype```)

In [ ]:
# Z = np.zeros(10, [ ('position', [ ('x', float, 1),
#                                   ('y', float, 1)]),
#                    ('color',    [ ('r', float, 1),
#                                   ('g', float, 1),
#                                   ('b', float, 1)])])
# print (Z)

#### 52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离(★★☆) 
(**提示**: ```np.atleast_2d, T, np.sqrt)```

In [15]:
Z = np.random.random((4,2))
Z
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
X,Y
# X-X.T
# D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
# print (D)
# ?np.atleast_2d

(array([[0.07646937, 0.1461058 , 0.1716806 , 0.84486718]]),
 array([[0.49833712, 0.8029313 , 0.25846578, 0.67714195]]))

In [11]:
# # 方法2
# # Much faster with scipy
import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
# import scipy.spatial
# D = scipy.spatial.distance.cdist(Z,Z)
# print (D)

#### 53. 如何将32位的浮点数(```float```)转换为对应的整数(```integer```)?
(**提示**: ```astype(copy=False)```)

In [18]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. 如何读取以下文件? (★★☆) 
(**提示**: ```np.genfromtxt```)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

[参考链接](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html)

#### 55. 对于```numpy```数组，```enumerate```的等价操作是什么？(★★☆) 
(**提示**: ```np.ndenumerate, np.ndindex```)

In [ ]:
# Z = np.arange(9).reshape(3,3)
# for index, value in np.ndenumerate(Z):
#     print (index, value)
# for index in np.ndindex(Z.shape):
#     print (index, Z[index])

#### 56. 生成一个通用的二维Gaussian-like数组 (★★☆) 
(**提示**: ```np.meshgrid, np.exp```)

In [ ]:
# X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
# D = np.sqrt(X*X+Y*Y)
# sigma, mu = 1.0, 0.0
# G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
# print (G)

#### 57. 对一个二维数组，如何在其内部随机放置p个元素? (★★☆) 
(**提示**: ```np.put, np.random.choice```)

In [12]:
# n = 10
# p = 3
# Z = np.zeros((n,n))
# np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
# print (Z)
?np.put

#### 58. 减去一个矩阵中的每一行的平均值 (★★☆) 
(**提示**: ```mean(axis=,keepdims=)```)

In [16]:
X = np.random.rand(5, 10)
# # Recent versions of numpy
# Y = X - X.mean(axis=1, keepdims=True)
# print(Y)
X.mean(axis=1, keepdims=False)

array([0.54463317, 0.47583288, 0.57535828, 0.5114838 , 0.3418089 ])

In [ ]:
# # 方法2
# # Older versions of numpy
# Y = X - X.mean(axis=1).reshape(-1, 1)
# print (Y)

#### 59. 如何通过第n列对一个数组进行排序? (★★☆) 
(**提示**: ```argsort```)

In [ ]:
# Z = np.random.randint(0,10,(3,3))
# print (Z)
# print (Z[Z[:,1].argsort()])

#### 60. 如何检查一个二维数组是否有空列？(★★☆) 
(**提示**: ```any, ~```)

In [24]:
Z = np.random.randint(0,3,(3,10))
Z
# print ((~Z.any(axis=0)).any())


array([[1, 2, 0, 2, 1, 0, 1, 1, 2, 0],
       [0, 0, 0, 2, 1, 0, 1, 1, 2, 1],
       [2, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [28]:
Z.any(axis=0)

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

#### 61. 从数组中的给定值中找出最近的值 (★★☆) 
(**提示**: ```np.abs, argmin, flat```)

In [32]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
n = Z[np.abs(Z - z).argmin()]
print (m,n)

0.573786398983858 0.573786398983858


#### 62. 如何用迭代器(```iterator```)计算两个分别具有形状(1,3)和(3,1)的数组? (★★☆) 
(**提示**: ```np.nditer```)

In [39]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
A,B

(array([[0],
        [1],
        [2]]),
 array([[0, 1, 2]]))

In [47]:
it = np.nditer([A,B,None])
for x,y,z in it: 
    z = x + y
#     print(x,y,z)
print (it.operands[2])
# z
# ?np.nditer.operands

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. 创建一个具有```name```属性的数组类(★★☆) 
(**提示**: ```class```方法)

In [ ]:
# class NamedArray(np.ndarray):
#     def __new__(cls, array, name="no name"):
#         obj = np.asarray(array).view(cls)
#         obj.name = name
#         return obj
#     def __array_finalize__(self, obj):
#         if obj is None: return
#         self.info = getattr(obj, 'name', "no name")

# Z = NamedArray(np.arange(10), "range_10")
# print (Z.name)

#### 64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? (★★★) 
(**提示**: ```np.bincount | np.add.at```)

In [ ]:
# Z = np.ones(10)
# I = np.random.randint(0,len(Z),20)
# Z += np.bincount(I, minlength=len(Z))
# print(Z)

In [ ]:
# # 方法2
# np.add.at(Z, I, 1)
# print(Z)

#### 65. 根据索引列表(```I```)，如何将向量(```X```)的元素累加到数组(```F```)? (★★★) 
(**提示**: ```np.bincount```)

In [48]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. 考虑一个```(dtype=ubyte)``` 的 ```(w,h,3)```图像，计算其唯一颜色的数量(★★★) 
(**提示**: ```np.unique```)

In [ ]:
# w,h = 16,16
# I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
# #Note that we should compute 256*256 first. 
# #Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
# F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
# n = len(np.unique(F))
# print (n)

#### 67. 考虑一个四维数组，如何一次性计算出最后两个轴(```axis```)的和？ (★★★) 
(**提示**: ```sum(axis=(-2,-1))```)

In [62]:
A = np.random.randint(0,10,(2,2,2,2))
# # solution by passing a tuple of axes (introduced in numpy 1.7.0)
print(A)
_sum = A.sum(axis=(-2,-1))
# _sum
print (_sum)

[[[[5 6]
   [8 2]]

  [[7 0]
   [2 3]]]


 [[[1 3]
   [3 5]]

  [[6 5]
   [5 4]]]]
[[21 12]
 [12 20]]


In [ ]:
# # 方法2
# sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
# print (sum)

#### 68. 考虑一个一维向量```D```，如何使用相同大小的向量```S```来计算```D```子集的均值？(★★★) 
(**提示**: ```np.bincount```)

In [ ]:
# D = np.random.uniform(0,1,100)
# S = np.random.randint(0,10,100)
# D_sums = np.bincount(S, weights=D)
# D_counts = np.bincount(S)
# D_means = D_sums / D_counts
# print (D_means)

In [ ]:
# # 方法2
# import pandas as pd
# print(pd.Series(D).groupby(S).mean())

#### 69. 如何获得点积 ```dot prodcut```的对角线? (★★★) 
(**提示**: ```np.diag```)

In [2]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([1.74580509, 2.08712775, 1.87204694, 0.96230619, 1.3974027 ])

In [5]:
# 方法2
# Fast version
np.sum(A * B.T, axis=1)


array([1.74580509, 2.08712775, 1.87204694, 0.96230619, 1.3974027 ])

In [6]:
# 方法3
# Faster version
np.einsum("ij,ji->i", A, B)

array([1.74580509, 2.08712775, 1.87204694, 0.96230619, 1.3974027 ])

#### 70. 考虑一个向量```[1,2,3,4,5]```,如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？(★★★) 
(**提示**: ```array[::4]```)

In [103]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0
# Z0[::nz+1] = Z
# print (Z0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？(★★★) 
(**提示**: ```array[:, :, None]```)

In [ ]:
# A = np.ones((5,5,3))
# B = 2*np.ones((5,5))
# print (A * B[:,:,None])

#### 72. 如何对一个数组中任意两行做交换? (★★★) 
(**提示**: ```array[[]] = array[[]]```)

In [93]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment   
Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)     
(**提示**: ```repeat, np.roll, np.sort, view, np.unique```)

In [ ]:
# faces = np.random.randint(0,100,(10,3))
# F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
# F = F.reshape(len(F)*3,2)
# F = np.sort(F,axis=1)
# G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
# G = np.unique(G)
# print (G)

#### 74. 给定一个二进制的数组```C```，如何产生一个数组```A```满足```np.bincount(A)==C```(★★★) 
(**提示**: ```np.repeat```)

In [ ]:
# C = np.bincount([1,1,2,3,4,4,6])
# A = np.repeat(np.arange(len(C)), C)
# print (A)

#### 75. 如何通过滑动窗口计算一个数组的平均数? (★★★) 
(**提示**: ```np.cumsum```)

In [ ]:
# def moving_average(a, n=3) :
#     ret = np.cumsum(a, dtype=float)
#     ret[n:] = ret[n:] - ret[:-n]
#     return ret[n - 1:] / n
# Z = np.arange(20)

# print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)     
(**提示**: ```from numpy.lib import stride_tricks```)

In [ ]:
# from numpy.lib import stride_tricks

# def rolling(a, window):
#     shape = (a.size - window + 1, window)
#     strides = (a.itemsize, a.itemsize)
#     return stride_tricks.as_strided(a, shape=shape, strides=strides)
# Z = rolling(np.arange(10), 3)

# print (Z)

#### 77. 如何对布尔值取反，或者原位(```in-place```)改变浮点数的符号(```sign```)？(★★★) 
(**提示**: ```np.logical_not, np.negative```)

In [ ]:
# Z = np.random.randint(0,2,100)
# np.logical_not(Z, out=Z)

In [ ]:
# Z = np.random.uniform(-1.0,1.0,100)
# np.negative(Z, out=Z)

#### 78. 考虑两组点集```P0```和```P1```去描述一组线(二维)和一个点```p```,如何计算点```p```到每一条线 i ```(P0[i],P1[i])```的距离？(★★★)

In [ ]:
# def distance(P0, P1, p):
#     T = P1 - P0
#     L = (T**2).sum(axis=1)
#     U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
#     U = U.reshape(len(U),1)
#     D = P0 + U*T - p
#     return np.sqrt((D**2).sum(axis=1))

# P0 = np.random.uniform(-10,10,(10,2))
# P1 = np.random.uniform(-10,10,(10,2))
# p  = np.random.uniform(-10,10,( 1,2))

# print (distance(P0, P1, p))

#### 79.考虑两组点集```P0```和```P1```去描述一组线(二维)和一组点集```P```，如何计算每一个点 ```j(P[j])``` 到每一条线 i ```(P0[i],P1[i]) ```的距离？(★★★)

In [ ]:
# # based on distance function from previous question
# P0 = np.random.uniform(-10, 10, (10,2))
# P1 = np.random.uniform(-10,10,(10,2))
# p = np.random.uniform(-10, 10, (10,2))
# print (np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
# Z = np.random.randint(0,10,(10,10))
# shape = (5,5)
# fill  = 0
# position = (1,1)

# R = np.ones(shape, dtype=Z.dtype)*fill
# P  = np.array(list(position)).astype(int)
# Rs = np.array(list(R.shape)).astype(int)
# Zs = np.array(list(Z.shape)).astype(int)

# R_start = np.zeros((len(shape),)).astype(int)
# R_stop  = np.array(list(shape)).astype(int)
# Z_start = (P-Rs//2)
# Z_stop  = (P+Rs//2)+Rs%2

# R_start = (R_start - np.minimum(Z_start,0)).tolist()
# Z_start = (np.maximum(Z_start,0)).tolist()
# R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
# Z_stop = (np.minimum(Z_stop,Zs)).tolist()

# r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
# z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
# R[r] = Z[z]
# print (Z)
# print (R)

#### 81. 考虑一个数组```Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]```,如何生成一个数组```R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]```? (★★★) 
(**提示**: ```stride_tricks.as_strided```)

In [ ]:
# Z = np.arange(1,15,dtype=np.uint32)
# R = stride_tricks.as_strided(Z,(11,4),(4,4))
# print (R)

#### 82. 计算一个矩阵的秩(★★★) 
(**提示**: ```np.linalg.svd```)

In [ ]:
# Z = np.random.uniform(0,1,(10,10))
# U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
# rank = np.sum(S > 1e-10)
# print (rank)

#### 83. 如何找到一个数组中出现频率最高的值？ 
(**提示**: ```np.bincount, argmax```)

In [77]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

2


#### 84. 从一个```10x10```的矩阵中提取出连续的```3x3```区块(★★★) 
(**提示**: ```stride_tricks.as_strided```)

In [ ]:
# Z = np.random.randint(0,5,(10,10))
# n = 3
# i = 1 + (Z.shape[0]-3)
# j = 1 + (Z.shape[1]-3)
# C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
# print (C)

#### 85. 创建一个满足 ```Z[i,j] == Z[j,i]```的子类 (★★★) 
(**提示**: ```class``` 方法)

In [ ]:
# class Symetric(np.ndarray):
#     def __setitem__(self, index, value):
#         i,j = index
#         super(Symetric, self).__setitem__((i,j), value)
#         super(Symetric, self).__setitem__((j,i), value)

# def symetric(Z):
#     return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

# S = symetric(np.random.randint(0,10,(5,5)))
# S[2,3] = 42
# print (S)

#### 86. 考虑p个 ```nxn``` 矩阵和一组形状为```(n,1)```的向量，如何直接计算p个矩阵的乘积```(n,1)```？(★★★) 
(**提示**: ```np.tensordot```)

In [ ]:
# p, n = 10, 20
# M = np.ones((p,n,n))
# V = np.ones((p,n,1))
# S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
# print (S)
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

#### 87. 对于一个```16x16```的数组，如何得到一个区域(```block-sum```)的和(区域大小为```4x4```)? (★★★) 
(**提示**: ```np.add.reduceat```)

In [ ]:
# Z = np.ones((16,16))
# k = 4
# S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
#                                        np.arange(0, Z.shape[1], k), axis=1)
# print (S)

#### 88. 如何利用```numpy```数组实现Game of Life? (★★★)
(**提示**: [Game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life))

In [ ]:
# def iterate(Z):
#     # Count neighbours
#     N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
#          Z[1:-1,0:-2]                + Z[1:-1,2:] +
#          Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

#     # Apply rules
#     birth = (N==3) & (Z[1:-1,1:-1]==0)
#     survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
#     Z[...] = 0
#     Z[1:-1,1:-1][birth | survive] = 1
#     return Z

# Z = np.random.randint(0,2,(50,50))
# for i in range(100): Z = iterate(Z)
# print (Z)

#### 89. 如何找到一个数组的第n个最大值? (★★★) 
(**提示**: ```np.argsort | np.argpartition```)

In [75]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [76]:
# 方法2
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


#### 90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)(★★★) 
(**提示**: ```np.indices```)

In [72]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        print(arrays[n][ix[:, n]])
        ix[:, n] = arrays[n][ix[:, n]]
        
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[1 1 1 1 2 2 2 2 3 3 3 3]
[4 4 5 5 4 4 5 5 4 4 5 5]
[6 7 6 7 6 7 6 7 6 7 6 7]
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [70]:
ix = np.indices((3,2,2), dtype=int)
ix = ix.reshape(-1, 3)
ix2 = ix.reshape(3, -1).T
ix2

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       [2, 0, 0],
       [2, 0, 1],
       [2, 1, 0],
       [2, 1, 1]])

#### 91. 如何从一个正常数组创建记录数组(```record array```)? (★★★) 
(**提示**: ```np.core.records.fromarrays```)

In [38]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)
Z

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


array([['Hello', '2.5', '3'],
       ['World', '3.6', '2']], dtype='<U5')

#### 92. 考虑一个大向量```Z```, 用三种不同的方法计算它的立方(★★★) 
(**提示**: ```np.power, \*, np.einsum```)

In [28]:
x = np.random.rand(3)
np.power(x,3)

array([4.99088811e-01, 4.13026019e-03, 2.62879777e-04])

In [29]:
# 方法2
x*x*x

array([4.99088811e-01, 4.13026019e-03, 2.62879777e-04])

In [34]:
# 方法3
import torch
x = np.random.rand(3)
np.einsum('i,i,i->i',x,x,x)

array([0.33260559, 0.02648258, 0.00246535])

#### 97. 考虑两个向量```A```和```B```，写出用```einsum```等式对应的```inner, outer, sum, mul```函数(★★★) 
(**提示**: [```np.einsum```](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.einsum.html))

In [6]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
A,B
print ('sum')
print (np.einsum('i->', A))# np.sum(A)
A,B

sum
4.8956481175529865


(array([0.8211363 , 0.72119493, 0.03556142, 0.19815726, 0.238385  ,
        0.13412556, 0.99941409, 0.5172103 , 0.50184359, 0.72861965]),
 array([0.89064736, 0.45573023, 0.23966881, 0.26845398, 0.86706865,
        0.16877249, 0.15007112, 0.72166297, 0.23302594, 0.19175067]))

In [4]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

A * B
[0.97928483 0.37397743 0.25449383 0.03913797 0.21706847 0.33398919
 0.1985917  0.57872284 0.11827462 0.54704777]


In [7]:
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

inner
2.130955737549311


In [8]:
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

outer
[[0.73134288 0.37421664 0.19680076 0.22043731 0.71198155 0.13858522
  0.12322884 0.59258366 0.19134606 0.15745344]
 [0.64233036 0.32867033 0.17284793 0.19360765 0.62532552 0.12171786
  0.10823053 0.52045968 0.16805713 0.13828961]
 [0.03167269 0.01620641 0.00852296 0.0095466  0.03083419 0.00600179
  0.00533674 0.02566336 0.00828673 0.00681893]
 [0.17648824 0.09030626 0.04749212 0.05319611 0.17181595 0.03344349
  0.02973768 0.14300276 0.04617578 0.03799679]
 [0.21231697 0.10863925 0.05713345 0.0639954  0.20669616 0.04023283
  0.0357747  0.17203363 0.05554989 0.04571048]
 [0.11945858 0.06112507 0.03214571 0.03600654 0.11629607 0.0226367
  0.02012837 0.09679345 0.03125474 0.02571867]
 [0.89012552 0.45546321 0.23952839 0.26829669 0.86656063 0.1686736
  0.14998319 0.72124014 0.23288941 0.19163832]
 [0.46065199 0.23570837 0.12395918 0.13884716 0.44845684 0.08729087
  0.07761833 0.37325152 0.12052342 0.09917542]
 [0.44696567 0.2287053  0.12027626 0.13472191 0.43513285 0.08469739
  0.0753